### PR TITLE
Added graph showing intra-subject variability (COV) as a function of atrophy estimation error

### LINKED ISSUE #86: Add graph showing intra-subject variability (STD) as a function of atrophy estimation error
Once the graph is done, we should identify the 5-10 subjects with worse STD, and see if they are associated with strong movements/artifacts.

If that's the case, it should be reported as a new finding in the manuscript.

### PR DESCRIPTION
**Pull request by PaulBautin**
I have opened this PR to present code used to generate figures in issue #86.

DONE:
- Added graphs showing intra-subject variability (COV) as a function of atrophy estimation error
- save output dataframes in a csv files

Fixes #86

### CODE REVIEW

**Comment by PaulBautin** [comment]
The following graphs are briefly introduced in the supplementary material of the manuscript and are only used to prove some of are hypotheses wrong. Should they be kept and merged? @jcohenadad 
(Note: the results represented here are not the the results that will be published)
fig_err_in_function_of_cov

The following graph shows the non-correlation of t1w outliers (red dots) and t2w outliers (green dots)
fig_err_in_function_of_cov_outlier

**Comment by jcohenadad** [comment]
> Should they be kept and merged?

hum... good question... just to be sure: you're talking about the additional functions (error_function_of_intra_cov*), right? I think it doesn't hurt to keep them in the main branch. The functions are well documented, and pretty "standalone". What do you think?

**Comment by PaulBautin** [comment]
Indeed, I am talking about the additional functions (error_function_of_intra_cov*). I agree that it would not hurt to keep these new functions in the main branch -- even more so because they are optional when running `csa_rescale_stat.py`.

In last commit https://github.com/sct-pipeline/csa-atrophy/pull/87/commits/ae450922c302b41fb8ac52e369f2d2f9cf02b873, I have removed the following feature because it has become obsolete (there are no more missing CSAs).

>     * Test removing subjects with missing CSA: Presently if CSA is not computed the vertebrae levels are removed from the dataframe, I tried to see what happens when the entire subject is removed. It seems to eliminate values with high COV and low error % improving the correlation between these two metrics.

**Review by jcohenadad — APPROVED** [review]
thanks! great addition

**Pull request merged**
