### PR TITLE
Various improvements

### LINKED ISSUE #26: Indicate user to fetch dataset from spine generic
"csa-atrophy" dataset is no longer hosted on "openneuro" but on "spine generic project", https://github.com/spine-generic.

TODO:
- update README
- update csa_fetch_dataset

### LINKED ISSUE #29: manual_labeling_correction with python
'"/manual_labeling_correction.sh" is outdated by new python script present on spine generic: spine-generic/spine-generic#103. Once the python script in spine-generic is completed csa-atrophy should upgrade to new process.

### LINKED ISSUE #32: Manual labelling correction
When vertebral labelling works, each vertebra is labelled. However, manual correction of labelling currently uses spine-generic that requests user to manually input only 2 labels. How should i process labelling using the manual correction that contains only 2 labels?
Initial comment:
https://github.com/sct-pipeline/csa-atrophy/pull/31#issuecomment-670941179

### LINKED ISSUE #35: segment twice when rescale=1
When computing stats for rescale=1 ==> perc_diff=0. This is not a normal behavior. When image is transformed it is re-segmented this not the case when rescale=1 which explains perc_diff=0.
Image must be segmented twice (for rescale 1)to account for the variation of CSA due to image transformation. Name one segmentation "gt" and the other "1.0"

### LINKED ISSUE #36: underestimated inter-subject STD
In `csa_rescale_stat.py` inter-subject STD is under-estimated because transformed subjects were considered different subjects. To overcome this, mean CSA values over transformations (same subject) before computing intersubject STD.

### LINKED ISSUE #37: add flag -config in csa_rescale_stat
Path to config is hard coded in csa_rescale_stat. For clarity use flag -config in command line.

### LINKED ISSUE #40: Use spine-generic manual correction
Up to now shell script for manual correction was basic and did not offer very many options. With the use of a modified version of manual_correction.py from spine_generic https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/manual_correction.py csa-atrophy is now capable of correcting all files (labeling, and spinal cord segmentation). Moreover the use of spine generic allows a better organization of derivative files using BIDS convention.

For the use of spine_generic manual_correction.py script, modifications have to be made made:

- csa_atrophy_results/results folder is organized with one anat directory for each rescaling. manual_correction.py function check_file was modified to be able to find files.
- User is now asked with sct_label_utils to enter disks from 2 to 6 in the spinal cord. disk 2 ==> C2-C3

### PR DESCRIPTION
**Pull request by PaulBautin**
This PR does the following:
- correct issue #26 by indicating user via README to fetch dataset from spine-generic `https://github.com/spine-generic/data-multi-subject/archive/r20200801.zip` 
- correct issue for csa_rescale_stat.py (#35, #36, #37)
- freeze config files and README for spine-generic dataset processing 

List of TODO:

- [x] use the sct_run_batch variables PATH_RESULTS and PATH_DATA_PROCESSED in process_data.sh

- [x] make csa_rescale_stat.py part of setup.py

- [x] use only one vertebral labeling (rescale = 1) per subject in process_data.sh

- [x] Verify transfo_values.csv can be accessed when running process_data.sh in a new directory (ex: segmentation correction)

- [x] Use spine-generic manual correction #40

FIX #35, FIX #36, FIX #37, FIX #26, FIX #32, FIX #29, FIX #40

### CODE REVIEW

**Comment by PaulBautin** [comment]
@jcohenadad, i would need help to implement the manual correction. How do i process labelling using the manual correction that contains only 2 labels?

**Comment by jcohenadad** [comment]
> How do i process labelling using the manual correction that contains only 2 labels?

ok, so currently, spine-generic has manual manual labels with only 2 labels. You could e.g. use label 3, which corresponds to 2-3 disc (good for your study).

however, not ALL subjects have this label-- the ones where vertebral labeling worked don't have those labels. In that case you want to use the warped vertebral levels as a reference level for your study.

this is a fairly complex question (there are multiple solutions for it, but we need to chose carefully), which i think should deserve its own specific issue.

**Comment by jcohenadad** [comment]
@PaulBautin i don't understand the purpose of this PR. Could you explicit the title a bit more "fixes for first release" is not specific.

also, i see that this PR includes other PRs:
- merge of PR #28 "fetch dataset"
- merge of PR #30 "large dataset computing" and correction

This is now how GH workflow works. I think I already mentioned it in a previous PR that you should not include a PR in another PR. All PR should be based of the master branch. That's it. No dependencies with other branches please.

So, the proper workflow is:
- you have issue A
- you fix issue A in PR a
- you merge PR a into master
- you have issue B
- you fix issue B in PR b
- you merge PR b into master
…

please *always* follow this scheme.

this means: close this PR (because it does not follow this scheme) and create a specific PR **without** inclusions from former PRs.

**Comment by PaulBautin** [comment]
> this is a fairly complex question (there are multiple solutions for it, but we need to chose carefully), which i think should deserve its own specific issue.

I have opened an issue on this subject #32 

> Could you explicit the title a bit more "fixes for first release" is not specific.

My intention with this PR was to gather final fixes and release a version containing config to process spine-generic dataset.

> this means: close this PR (because it does not follow this scheme) and create a specific PR **without** inclusions from former PRs.

These former PRs were never merged to master . Should i close this PR and dispatch its elements for clarity (I can still use #30 ).

**Pull request merged**
