### PR TITLE
Crop around transformed segmentation

### LINKED ISSUE #88: Re-introduce padding in transformation
Images with missing CSA reported in issue #86  all present segmentations that do not cover all vertebrae levels from C3 to C5. This issue only appeared once padding was removed. Therefore, my guess is that segmentation is not performed when cord approaches the image boundaries. I do not think this issue is causing outliers presented in issue #83, because as mentioned in issue #86 removing subjects with missing CSA mostly removes subjects with high COV and low error. 

@jcohenadad, What do yout think of re-integrate padding to see if it resolves this issue?

example:
Cropped and transformed image:
[sub-barcelona04_T1w_RPI_r_crop_r0.98_t1.zip](https://github.com/sct-pipeline/csa-atrophy/files/5435226/sub-barcelona04_T1w_RPI_r_crop_r0.98_t1.zip)
segmentation of ^ image
[sub-barcelona04_T1w_RPI_r_crop_r0.98_t1_seg.zip](https://github.com/sct-pipeline/csa-atrophy/files/5435227/sub-barcelona04_T1w_RPI_r_crop_r0.98_t1_seg.zip)

### PR DESCRIPTION
**Pull request by PaulBautin**
This PR aims to implement: https://github.com/sct-pipeline/csa-atrophy/issues/88#issuecomment-716824280. Up to know cropping was performed around a dilated initial segmentation. The new method transforms initial segmentation before cropping image, this ensures spinal cord does not exceed image boundaries.

DONE:
- transform and dilate the labelled segmentation to crop image
- update csa_rescale_stat.py, extract the "rescale" from updated "Filename"

FIX #88

### CODE REVIEW

**Comment by jcohenadad** [comment]
@PaulBautin is it ready for review?

**Comment by PaulBautin** [comment]
Yes, it was tested on a 2 subjects that caused issues in precedent runs.

**Comment by PaulBautin** [comment]
@jcohenadad, could you have a look when you find the time?

**Comment by jcohenadad** [comment]
@PaulBautin i'm looking into that now

> Yes, it was tested on a 2 subjects that caused issues in precedent runs.

can you pls specify the 2 subjects you are talking about? i'm trying to reproduce

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
