### PR TITLE
Correction of various issues after first large compute

### LINKED ISSUE #51: Very large QC file
When running several transfo iterations, rescaling factors over the 250 subjects, the output zipped QC file end up being several GB large, which is not convenient for copying across servers.

Given that not all QC outputs are necessary, maybe we could only generate the QC for the vertebral labeling, and the first segmentation (untransformed, un-rescaled)?

### LINKED ISSUE #52: Profiling on OpenMP Compute Canada cluster
The OpenMP method (vs. MPI) restricts the number of jobs per node. Currently, 32 jobs is the maximum, meaning that 32 subjects can be processed in parallel. It would be nice to break the processing across chunks of 32 subjects to accelerate the processing.

For the records, on `graham`, the following config took 7h36min to complete:
- number of subjects: 260
- number of iterations: 5
- number of rescaling: 4

The computation time per subject varies between ~1h and ~2.5h.

Here is the batch log: 
[log_results_csa_t1_20200822.zip](https://github.com/sct-pipeline/csa-atrophy/files/5117820/log_results_csa_t1_20200822.zip)

### PR DESCRIPTION
**Pull request by PaulBautin**
DONE
- Display the time after each command in iteration loop #52 
- Only generate the QC for the vertebral labeling, and the first segmentation (untransformed, un-rescaled) #51 

FIX #51 FIX #52

### CODE REVIEW

**Comment by jcohenadad** [comment]
@PaulBautin could you pls display an example of timing you got? so we can compare with compute canada outputs

**Comment by PaulBautin** [comment]
Test on 2 subjects, 1 rescaling, 2 transfo
Total Duration: 00h03m40s

**results for sub-amu01 (results were almost identical):** 

TIME: Duration of segmentation on non cropped image:    0hrs 1min 3sec
TIME: Duration of labelling:    0hrs 1min 19sec

**RESCALING = 1**
TIME: Duration of image transfo t1:    0hrs 0min 1sec
TIME: Duration of labelling transfo t1:    0hrs 0min 4sec
TIME: Duration of segmentation t1:    0hrs 0min 6sec
TIME: Duration of sct_process_segmentation t1:    0hrs 0min 6sec

TIME: Duration of of image transfo t2:    0hrs 0min 1sec
TIME: Duration of labelling transfo t2:    0hrs 0min 3sec
TIME: Duration of segmentation t2:    0hrs 0min 6sec
TIME: Duration of sct_process_segmentation t2:    0hrs 0min 5sec

**RESCALING = 0.95**
TIME: Duration of image transfo t1:    0hrs 0min 2sec
TIME: Duration of labelling transfo t1:    0hrs 0min 3sec
TIME: Duration of segmentation t1:    0hrs 0min 6sec
TIME: Duration of sct_process_segmentation t1:    0hrs 0min 6sec

TIME: Duration of image transfo t2:    0hrs 0min 1sec
TIME: Duration of labelling transfo t2:    0hrs 0min 3sec
TIME: Duration of segmentation t2:    0hrs 0min 6sec
TIME: Duration of sct_process_segmentation t2:    0hrs 0min 6sec

**Comment by jcohenadad** [comment]
@PaulBautin can you please indicate hardware specs in your post above (RAM, number of CPU cores, clock)

**Comment by jcohenadad** [comment]
@PaulBautin here is the output from compute canada (one subject): can you please clean up the other verbose: https://pastebin.com/ihUhcvBc

**Comment by PaulBautin** [comment]
@jcohenadad, I do not understant what you mean by other verbose? Do you want to remove other verbose than https://github.com/sct-pipeline/csa-atrophy/pull/53#issuecomment-679212632 in pastebin?

**Comment by jcohenadad** [comment]
> @jcohenadad, I do not understant what you mean by other verbose? Do you want to remove other verbose than [#53 (comment)](https://github.com/sct-pipeline/csa-atrophy/pull/53#issuecomment-679212632) in pastebin?

just curate the pastbin i made to only show the TIME items for easy comparison with https://github.com/sct-pipeline/csa-atrophy/pull/53#issuecomment-679212632

**Comment by PaulBautin** [comment]
**results from compute canada on sub-unf06**
SCT info:
- version: git-master-253936cfc07712c587d9f4cfbbcb760f151172f0
- path: /home/jcohen/sct
OS: linux (Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core)
CPU cores: Available: 32, Used by SCT: 1
RAM: MemTotal:       527986272 kB
total        used        free      shared  buff/cache   available
Mem:         515611      121291      342871        3724       51448      384671
Swap:         10239         648        9591

TIME: Duration of reorienting and resampling:    0hrs 0min 17sec
TIME: Duration of segmentation on non cropped image:    0hrs 2min 13sec
TIME: Duration of labelling:    0hrs 2min 21sec

**RESCALING = 1**
TIME: Duration of of image transfo t1:    0hrs 0min 3sec
TIME: Duration of labelling transfo t1:    0hrs 0min 4sec
TIME: Duration of segmentation t1:    0hrs 0min 18sec
TIME: Duration of sct_process_segmentation t1:    0hrs 0min 11sec

TIME: Duration of of image transfo t2:    0hrs 0min 2sec
TIME: Duration of labelling transfo t2:    0hrs 0min 3sec
TIME: Duration of segmentation t2:    0hrs 0min 19sec
TIME: Duration of sct_process_segmentation t2:    0hrs 0min 10sec

TIME: Duration of of image transfo t3:    0hrs 0min 2sec
TIME: Duration of labelling transfo t3:    0hrs 0min 3sec
TIME: Duration of segmentation t3:    0hrs 0min 19sec
TIME: Duration of sct_process_segmentation t3:    0hrs 0min 10sec

**RESCALING = 0.99**
TIME: Duration of of image transfo t1:    0hrs 0min 2sec
TIME: Duration of labelling transfo t1:    0hrs 0min 4sec
TIME: Duration of segmentation t1:    0hrs 0min 19sec
TIME: Duration of sct_process_segmentation t1:    0hrs 0min 11sec

TIME: Duration of of image transfo t2:    0hrs 0min 2sec
TIME: Duration of labelling transfo t2:    0hrs 0min 4sec
TIME: Duration of segmentation t2:    0hrs 0min 19sec
TIME: Duration of sct_process_segmentation t2:    0hrs 0min 11sec

TIME: Duration of of image transfo t3:    0hrs 0min 2sec
TIME: Duration of labelling transfo t3:    0hrs 0min 4sec
TIME: Duration of segmentation t3:    0hrs 0min 19sec
TIME: Duration of sct_process_segmentation t3:    0hrs 0min 11sec

**Comment by jcohenadad** [comment]
ok, so about 30s/iteration. still far from the 4-9min per iteration reported in https://github.com/sct-pipeline/csa-atrophy/issues/52#issuecomment-679104617. 

Maybe this is due to the number of subjects. Let's approve this PR, wait for a fix to https://github.com/neuropoly/spinalcordtoolbox/issues/2859 and then i will re-run a processing (now with the profiling).

**Comment by PaulBautin** [comment]
> Let's approve this PR, wait for a fix to [neuropoly/spinalcordtoolbox#2859](https://github.com/neuropoly/spinalcordtoolbox/issues/2859) and then i will re-run a processing (now with the profiling).

Sounds good. I've implemented the quick fix from https://github.com/neuropoly/spinalcordtoolbox/issues/2859#issuecomment-679207356, could you describe the fix you are waiting for?

**Comment by jcohenadad** [comment]
> I've implemented the quick fix from neuropoly/spinalcordtoolbox#2859 (comment), could you describe the fix you are waiting for?

where did you implement it? i don't see a PR (should be specific PR)

**Comment by jcohenadad** [comment]
ah! i see you've implemented in this PR

again, again, again: PR should be specific to an issue, not a dump for many corrections that are unrelated to each other.

**Comment by PaulBautin** [comment]
I have re-arranged the PR. @jcohenadad, could you review?

**Pull request merged**
